---
title: "Results"
author: "Koen Hufkens"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Results}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include = FALSE}
library(dplyr)
library(ggplot2)
library(reactable)
options(dplyr.summarise.inform = FALSE)
```

Summary results of training FCN / LSTM models on 150 epochs.


```{r echo = FALSE, warning = FALSE, message=FALSE}
# read in the modelled data
df_lstm <- readRDS(here::here("data/leave_site_out_output_lstm.rds")) |>
  rename(
    "GPP_pred_lstm" = "GPP_pred"
  )
df_fcn <- readRDS(here::here("data/leave_site_out_output_fcn.rds")) |>
  rename(
    "GPP_pred_fcn" = "GPP_pred"
  )

# read in the original input data
orig <- readRDS(here::here("data/df_imputed.rds"))

# join data
df <- left_join(df_lstm, df_fcn)
df <- left_join(df, orig) |>
  mutate(
    date = as.Date(date)
  )

# merge python results (paper)
df_python <- read.csv(here::here("data/LSTM_nocondition_results_apr22.csv")) |>
  mutate(
    date = as.Date(date)
  ) |>
  rename(
    "GPP_pred_python" = "lstm_cond0"
  ) |>
  select(
    sitename,
    date,
    GPP_pred_python
  )

df <- left_join(df, df_python)

# R squared and RMSE global
statistics_global <- df |>
  summarize(
    R2_lstm = summary(lm(GPP_pred_lstm ~ GPP_NT_VUT_REF))$r.squared,
    RMSE_lstm = sqrt(mean((GPP_pred_lstm - GPP_NT_VUT_REF)^2, na.rm = TRUE)),
    MAE_lstm = abs(mean((GPP_pred_lstm - GPP_NT_VUT_REF), na.rm = TRUE)),
    R2_fcn = summary(lm(GPP_pred_fcn ~ GPP_NT_VUT_REF))$r.squared,
    RMSE_fcn = sqrt(mean((GPP_pred_fcn - GPP_NT_VUT_REF)^2, na.rm = TRUE)),
    MAE_fcn = abs(mean((GPP_pred_fcn - GPP_NT_VUT_REF), na.rm = TRUE)),
    R2_python = summary(lm(GPP_pred_python ~ GPP_NT_VUT_REF))$r.squared,
    RMSE_python = sqrt(mean((GPP_pred_python - GPP_NT_VUT_REF)^2, na.rm = TRUE)),
    MAE_python = abs(mean((GPP_pred_python - GPP_NT_VUT_REF), na.rm = TRUE))
  ) |>
  round(3)

reactable::reactable(statistics_global)
```

```{r echo = FALSE, , warning = FALSE}
# R squared and RMSE by site
statistics_sites <- df |>
  group_by(sitename, koeppen_code) |>
  summarize(
    R2_lstm = summary(lm(GPP_pred_lstm ~ GPP_NT_VUT_REF))$r.squared,
    RMSE_lstm = sqrt(mean((GPP_pred_lstm - GPP_NT_VUT_REF)^2, na.rm = TRUE)),
    MAE_lstm = abs(mean((GPP_pred_lstm - GPP_NT_VUT_REF), na.rm = TRUE)),
    R2_fcn = summary(lm(GPP_pred_fcn ~ GPP_NT_VUT_REF))$r.squared,
    RMSE_fcn = sqrt(mean((GPP_pred_fcn - GPP_NT_VUT_REF)^2, na.rm = TRUE)),
    MAE_fcn = abs(mean((GPP_pred_fcn - GPP_NT_VUT_REF), na.rm = TRUE)),
    R2_python = summary(lm(GPP_pred_python ~ GPP_NT_VUT_REF))$r.squared,
    RMSE_python = sqrt(mean((GPP_pred_python - GPP_NT_VUT_REF)^2, na.rm = TRUE)),
    MAE_python = abs(mean((GPP_pred_python - GPP_NT_VUT_REF), na.rm = TRUE))
  ) |>
  mutate(
    across(where(is.double),
    \(x) round(x, 3)
    )
  )

reactable::reactable(statistics_sites)
```

```{r echo = FALSE, warning=FALSE}

seasonal_mean <- df |>
  mutate(
    doy = as.numeric(format(date, "%j"))
  ) |>
  group_by(doy, koeppen_code) |>
  summarize(
    GPP_pred_lstm_mean = mean(GPP_pred_lstm),
    GPP_pred_fcn_mean = mean(GPP_pred_fcn),
    GPP_pred_python_mean = mean(GPP_pred_python),
    GPP_obs_mean = mean(GPP_NT_VUT_REF)
  ) |>
  tidyr::pivot_longer(
    cols = starts_with("GPP"),
    names_to = "source",
    values_to = "GPP"
  )
  
# plot all validation graphs
p <- ggplot(seasonal_mean) +
  geom_line(
    aes(
      doy,
      GPP,
      group = source,
      colour = source
    )
  ) +
  labs(
    x = "DOY",
    y = "GPP"
  ) +
  theme_bw() +
  facet_wrap(
    ~ koeppen_code,
    ncol = 4
    )

print(p)
```

```{r echo = FALSE, warning=FALSE}
statistics_sites_long <- statistics_sites |>
  select(
    starts_with("R2"),
    sitename,
    koeppen_code
  ) |>
  tidyr::pivot_longer(
    cols = starts_with("R2"),
    names_to = "R2",
    values_to = "value"
  )

# plot all validation graphs
p <- ggplot(statistics_sites_long) +
  geom_boxplot(
    aes(
      koeppen_code,
      value,
      fill = R2
    )
  ) +
  theme_bw()

print(p)
```

